title: Android-Base-MVP
description: Android Base MVP Concept with RXJava, Dagger, Event Bus, Retrofit, Glide, OkHTTP
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
